# File: e-commerce/global-config.yml
spring:
  datasource:
    username: postgres
    password: postgres
  rabbitmq:
    username: guest
    password: guest
  mail:
    username: projekttesting12657@gmail.com
    password: wrpg glau haqx jhog
    host: smtp.gmail.com
    port: 587

db:
  host: localhost
  port: 5432
rabbitmq:
  host: localhost
  port: 5672
  
jwt:
  secret: my-super-secret-key-that-is-now-managed-globally

services:
  AuthService:
    url: http://localhost:8080
    server:
      port: 8080
  CatalogService:
    url: http://localhost:8081
    server:
      port: 8081
  InventoryService:
    url: http://localhost:8082
    server:
      port: 8082
  OrderService:
    url: http://localhost:8083
    server:
      port: 8083
  NotificationService:
    url: http://localhost:8084
    server:
      port: 8084
  BFFService:
    server:
      port: 8085
  PaymentService:
    url: http://localhost:8086
    server:
      port: 8086
  WelcomeNotificationService:
    url: http://localhost:8087
    server:
      port: 8087
