services:
  order-service:
    build: .
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/e_commerce_order_db
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: e_commerce_order_db
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_order_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management