apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  AUTH_DB_HOST: "{{AUTH_DB_HOST}}"
  ORDERS_DB_HOST: "{{ORDERS_DB_HOST}}"
  CATALOG_DB_HOST: "{{CATALOG_DB_HOST}}"

  RABBITMQ_HOST: "rabbitmq-svc"

  AUTH_SERVICE_URL: "http://auth-service-svc:8080"
  CATALOG_SERVICE_URL: "http://catalog-service-svc:8081"
