apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
stringData:
  POSTGRES_USER: "POSTGRES_USER"
  POSTGRES_PASSWORD: "POSTGRES_PASSWORD"

  RABBITMQ_USER: "RABBITMQ_USER"
  RABBITMQ_PASSWORD: "RABBITMQ_PASSWORD"

  JWT_SECRET: "BARDZO_DŁUGI_I_TAJNY_KLUCZ_DO_PODPISYWANIA_TOKENOW_JWT"

  MAIL_USERNAME: "twoj_login_do_serwera_smtp"
  MAIL_PASSWORD: "twoje_haslo_do_serwera_smtp"
  name: rabbitmq-secret
stringData:
  RABBITMQ_DEFAULT_USER: "mainuser"
  RABBITMQ_DEFAULT_PASSWORD: "zaq123"
