apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-secrets-provider
spec:
  provider: aws
  parameters:
    objects: |
      # ARN's for each secret from databases output
      - objectName: "__AUTH_SERVICE_SECRET_ARN__"
        jmesPath:
          - path: "password"
            objectAlias: "AUTH_SERVICE_DB_PASSWORD"

      - objectName: "__ORDER_SERVICE_SECRET_ARN__"
        jmesPath:
          - path: "password"
            objectAlias: "ORDER_SERVICE_DB_PASSWORD"

      - objectName: "__CATALOG_SERVICE_SECRET_ARN__"
        jmesPath:
          - path: "password"
            objectAlias: "CATALOG_SERVICE_DB_PASSWORD"

      - objectName: "__PAYMENT_SERVICE_SECRET_ARN__"
        jmesPath:
          - path: "password"
            objectAlias: "PAYMENT_SERVICE_DB_PASSWORD"

      - objectName: "__NOTIFICATION_SERVICE_SECRET_ARN__"
        jmesPath:
          - path: "password"
            objectAlias: "NOTIFICATION_SERVICE_DB_PASSWORD"

      - objectName: "__INVENTORY_SERVICE_SECRET_ARN__"
        jmesPath:
          - path: "password"
            objectAlias: "INVENTORY_SERVICE_DB_PASSWORD"
            
      - objectName: "__WELCOME_NOTIFICATION_SERVICE_SECRET_ARN__"
        jmesPath:
          - path: "password"
            objectAlias: "WELCOME_NOTIFICATION_SERVICE_DB_PASSWORD"
            
      - objectName: "__BFF_SERVICE_SECRET_ARN__"
        jmesPath:
          - path: "password"
            objectAlias: "BFF_SERVICE_DB_PASSWORD"
      - objectName: "__APP_SECRETS_ARN__"
        jmesPath:
          - path: "RABBITMQ_USER"
            objectAlias: "RABBITMQ_USER"
          - path: "RABBITMQ_PASSWORD"
            objectAlias: "RABBITMQ_PASSWORD"
          - path: "JWT_SECRET"
            objectAlias: "JWT_SECRET"
          - path: "MAIL_USERNAME"
            objectAlias: "MAIL_USERNAME"
          - path: "MAIL_PASSWORD"
            objectAlias: "MAIL_PASSWORD"



  # Creating kubernetes' secrets
  secretObjects:
  - secretName: auth-db-secret
    type: Opaque
    data:
    - key: POSTGRES_PASSWORD
      objectName: AUTH_SERVICE_DB_PASSWORD

  - secretName: order-db-secret
    type: Opaque
    data:
    - key: POSTGRES_PASSWORD
      objectName: ORDER_SERVICE_DB_PASSWORD

  - secretName: catalog-db-secret
    type: Opaque
    data:
    - key: POSTGRES_PASSWORD
      objectName: CATALOG_SERVICE_DB_PASSWORD

  - secretName: payment-db-secret
    type: Opaque
    data:
    - key: POSTGRES_PASSWORD
      objectName: PAYMENT_SERVICE_DB_PASSWORD

  - secretName: notification-db-secret
    type: Opaque
    data:
    - key: POSTGRES_PASSWORD
      objectName: NOTIFICATION_SERVICE_DB_PASSWORD

  - secretName: inventory-db-secret
    type: Opaque
    data:
    - key: POSTGRES_PASSWORD
      objectName: INVENTORY_SERVICE_DB_PASSWORD
      
  - secretName: welcome-notification-db-secret
    type: Opaque
    data:
    - key: POSTGRES_PASSWORD
      objectName: WELCOME_NOTIFICATION_SERVICE_DB_PASSWORD

  - secretName: bff-db-secret
    type: Opaque
    data:
    - key: POSTGRES_PASSWORD
      objectName: BFF_SERVICE_DB_PASSWORD

  - secretName: app-main-secrets
    type: Opaque
    data:
    - key: RABBITMQ_USER
      objectName: RABBITMQ_USER
    - key: RABBITMQ_PASSWORD
      objectName: RABBITMQ_PASSWORD
    - key: JWT_SECRET
      objectName: JWT_SECRET
    - key: MAIL_USERNAME
      objectName: MAIL_USERNAME
    - key: MAIL_PASSWORD
      objectName: MAIL_PASSWORD
