apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcomenotification-service-deployment
  labels:
    app: welcomenotification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: welcomenotification-service
  template:
    metadata:
      labels:
        app: welcomenotification-service
    spec:
      serviceAccountName: app-service-account
      containers:
      - name: welcomenotification-service
        image: "359850485340.dkr.ecr.eu-central-1.amazonaws.com/welcomenotification-service:latest"
        ports:
        - containerPort: 8087
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: welcomenotification-db-secret
# HealthCheck
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8087
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8087
          initialDelaySeconds: 30
          periodSeconds: 15

---
# dns/ports
apiVersion: v1
kind: Service
metadata:
  name: welcomenotification-service-svc
  labels:
    app: welcomenotification-service
spec:
  type: ClusterIP
  ports:
  - port: 8087
    targetPort: 8087
  selector:
    app: welcomenotification-service
